# yaml-language-server: $schema=https://raw.githubusercontent.com/ajmarkow/espanso-schema-json/master/schemas/Espanso_Config_File_Schema.json
#───────────────────────────────────────────────────────────────────────────────

filter_exec: WezTerm|iTerm|Visual Studio Code

# we exclude all trigger not starting by ":", to avoid conflict with vim mappings
extra_excludes:
  - "../match/expr.yml"
  - "../match/ligatures_emulation.yml"
  - "../match/spellcheck-fr.yml"
  - "../match/typography.yml"
