# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json
# DOCS https://espanso.org/docs/configuration/options/
# ───────────────────────────────────────────────────────────────────────────────

toggle_key: OFF
search_shortcut: off
show_icon: false
show_notifications: false
undo_backspace: true
