# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json
#───────────────────────────────────────────────────────────────────────────────

filter_title: Discord|Slack|Mattermost

extra_excludes:
  - "../match/emojis.yml" # already handled by the app itself

extra_includes:
  - "../match/_emoji-reacts.yml"
