# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/config.schema.json
#───────────────────────────────────────────────────────────────────────────────

# TODO: test for mattermost
filter_title: Discord|Slack|Mattermost

extra_includes:
  - "../match/_emoji-reacts.yml"
