set quiet := true

reload:
  sketchybar --reload

# constant reloading while development
# hotload:
#   sketchybar --hotload

start:
  brew services start sketchybar

# restart:
#   brew services restart sketchybar

stop:
  brew services stop sketchybar

docs:
  open "https://felixkratz.github.io/SketchyBar/config/bar"

