require("core.options")
require("core.utils")
require("core.keymaps")
require("core.commands")
require("core.autocmds")
-- require("core.abbreviations")
require("core.lazy")

-- require("neotex.core.options")
-- require("neotex.core.utils")
-- require("neotex.core.keymaps")
-- require("neotex.core.commands")
-- require("neotex.core.autocmds")
-- -- require("neotex.core.abbreviations")
-- require("neotex.core.lazy")
