# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json
# ───────────────────────────────────────────────────────────────────────────────

matches:
  # SOCIAL
  - trigger: ":name"
    replace: "Léo Guillon"

  - trigger: ":mpro"
    replace: "leo.guillon@icm-institute.org"

  - trigger: ":github"
    replace: "https://github.com/LeoGuillon"

  # ————————————————————————————————————————————————————————————————————————————
  # DATES
  - trigger: ":ajd"
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%d/%m/%Y"
  - trigger: ":iso"
    replace: "{{todayISO}}"
    vars:
      - name: todayISO
        type: date
        params:
          format: "%Y-%m-%d"
