# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json
# ───────────────────────────────────────────────────────────────────────────────

matches:
  - trigger: ":ajd"
    replace: "{{today}}"
    vars:
      - name: today
        type: date
        params:
          format: "%d/%m/%Y"
  - trigger: ":iso"
    replace: "{{todayISO}}"
    vars:
      - name: todayISO
        type: date
        params: { format: "%Y-%m-%d" }

